# Unified Deployment Configuration Template
# ========================================
#
# This is the master configuration for your sensor deployment.
# Copy this file to .deployment.yaml and customize for your environment.
#
# Quick Setup:
#   1. cp .deployment.template.yaml .deployment.yaml
#   2. Edit .deployment.yaml with your settings
#   3. Run: python3 setup_deployment.py (interactive setup)
#   OR manually edit and build directly
#
# Generate PSK (choose one method):
#   Python: python3 -c "import secrets; print(secrets.token_hex(32))"
#   Bash:   openssl rand -hex 32
#   Script: cd discovery-service && python3 generate_psk.py

# =============================================================================
# DEPLOYMENT INFORMATION
# =============================================================================
deployment:
  # Hostname prefix for sensors (will become SENSOR-01, SENSOR-02, etc)
  # Examples: HOMELAB, OFFICE, WAREHOUSE, LAB
  name: "SENSOR"

# =============================================================================
# DISCOVERY SERVICE CONFIGURATION
# =============================================================================
discovery_service:
  # IP address where discovery service will run
  # This is where Raspberry Pis will contact for registration
  # Examples: 192.168.1.100, 10.0.1.50, 172.16.0.10
  ip: "10.42.0.1"

  # Port for discovery service (default: 8080)
  port: 8080

  # Pre-shared key for device authentication (64 hex characters)
  # Generate with: python3 -c "import secrets; print(secrets.token_hex(32))"
  # Generate with: openssl rand -hex 32
  psk: "CHANGE_ME_TO_RANDOM_64_CHAR_HEX_STRING"

  # Admin API token for protected endpoints (for future use)
  # Generate with: python3 -c "import secrets; print(secrets.token_urlsafe(32))"
  admin_token: "CHANGE_ME_ADMIN_TOKEN"

# =============================================================================
# SENSOR CONFIGURATION REPOSITORY
# =============================================================================
bootstrap:
  # Git repository containing sensor NixOS configurations
  # This repo should contain your customized sensor configs
  # Format: github:username/repo-name or https://github.com/user/repo.git
  config_repo_url: "github:yearly1825/nixos-pi-configs"

# =============================================================================
# VPN CONFIGURATION (NETBIRD)
# =============================================================================
netbird:
  # Netbird setup key for automatic VPN enrollment
  # Get this from your Netbird dashboard: Setup Keys section
  # Each key can be used multiple times for device enrollment
  setup_key: "CHANGE_ME_TO_YOUR_NETBIRD_SETUP_KEY"

# =============================================================================
# SSH ACCESS CONFIGURATION
# =============================================================================
ssh_keys:
  # List of SSH public keys for sensor access
  # Add your public keys here (one per line)
  # Get your public key with: cat ~/.ssh/id_ed25519.pub
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... admin@example.com"
  # - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB... backup@example.com"

# =============================================================================
# NTFY NOTIFICATIONS (OPTIONAL)
# =============================================================================
ntfy:
  # Enable real-time notifications for bootstrap process
  enabled: false

  # NTFY topic URL where notifications will be sent
  # Public service: https://ntfy.sh/your-unique-topic-name
  # Self-hosted: https://your-ntfy-server.com/topic-name
  url: ""

  # Authentication type: none, basic, bearer
  auth_type: "none"

  # Basic authentication (only used if auth_type: basic)
  username: ""
  password: ""

  # Bearer token authentication (only used if auth_type: bearer)
  # token: "your-bearer-token-here"

  # Message priority for notifications
  # Options: min, low, default, high, urgent
  priority: "default"

  # Message tags for categorization
  tags: ["raspberry-pi", "bootstrap", "sensors"]

  # Retry settings for failed notifications
  retry_attempts: 3
  timeout_seconds: 10

# =============================================================================
# DISCOVERY SERVICE SECURITY SETTINGS
# =============================================================================
security:
  # Maximum registration attempts per IP address per hour
  max_requests_per_ip: 10

  # Maximum registration attempts per device per hour
  max_requests_per_device: 3

  # HMAC signature validity window in seconds (5 minutes = 300)
  signature_window_seconds: 300

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"

  # Log file path (relative to discovery-service directory)
  file: "logs/discovery.log"

  # Maximum log file size before rotation (MB)
  max_size_mb: 10

  # Number of backup log files to keep
  backup_count: 5

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
database:
  # SQLite database file for registration tracking
  # Path is relative to discovery-service directory
  file: "data/registrations.db"
