# Production Environment Configuration
# Secure configuration for production deployment

discovery_service:
  host: "0.0.0.0"
  port: 8000
  psk: "${DISCOVERY_PSK}"  # Load from environment variable
  database_path: "/app/data/discovery.db"

ntfy:
  enabled: true
  endpoint: "${NTFY_ENDPOINT}"  # Load from environment
  topic: "sensor-bootstrap-prod"
  auth_token: "${NTFY_AUTH_TOKEN}"  # Optional authentication

logging:
  level: "INFO"
  format: "json"
  file: "/app/logs/discovery.log"
  rotation: "daily"

# Production-specific settings
production:
  auto_confirm: false
  rate_limiting: true
  max_connections: 100
  timeout: 30
  metrics_enabled: true
  health_check_interval: 60  # seconds

# Security settings
security:
  max_registration_attempts: 5
  registration_cooldown: 300  # 5 minutes
  token_expiry: 3600  # 1 hour

# Performance settings
performance:
  database_pool_size: 10
  worker_processes: 4
  keep_alive_timeout: 5
