services:
  discovery-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ..:/app/parent:ro # Mount parent directory to access .deployment.yaml
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8080/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
