# Discovery Service Configuration

deployment:
  name: "SENSOR"  # Hostname prefix (will become SENSOR-01, SENSOR-02, etc)
  psk: "CHANGE_ME_TO_RANDOM_64_CHAR_HEX_STRING"  # Pre-shared key for device authentication

netbird:
  setup_key: "CHANGE_ME_TO_YOUR_NETBIRD_SETUP_KEY"  # Netbird VPN setup key

ssh_keys:
  # Add your SSH public keys here
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... admin@example.com"
  # - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB... backup@example.com"

security:
  max_requests_per_ip: 10          # Max registration attempts per IP
  max_requests_per_device: 3       # Max registration attempts per device serial
  signature_window_seconds: 300    # HMAC signature validity window (5 minutes)
  admin_token: "CHANGE_ME_ADMIN_TOKEN"  # Token for admin endpoints

api:
  host: "0.0.0.0"
  port: 8080

logging:
  level: "INFO"                    # DEBUG, INFO, WARNING, ERROR
  file: "logs/discovery.log"       # Log file path
  max_size_mb: 10                  # Max log file size before rotation
  backup_count: 5                  # Number of backup log files to keep

database:
  file: "data/registrations.db"    # SQLite database for tracking registrations

ntfy:
  enabled: false                   # Enable NTFY notifications
  url: ""                         # NTFY topic URL (e.g., https://ntfy.sh/your-topic)
  priority: "default"             # NTFY message priority
  tags: ["raspberry-pi", "bootstrap"]  # NTFY message tags
